comm1
igorkardin/aaa2 pull request #1
Opened 2022-09-16 09:55 UTC by igorkardin

2022-09-16 15:07 UTC, imadFndt requested changes

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/User.kt
> +    fun startTime(): LocalTime = LocalTime.now()
это че ленивое свойство?

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    var listOfUserFull = mutableListOf<User>()
зачем создал и сразу переприсвоил?

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    listOfUserFull = listOfUser.filter { it.type == Type.FULL } as MutableList<User>
зачем as MutableList

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    println(listOfUser.map(User::name).elementAt(0))
зачем весь список конвертировал, а потом взял первый
можно 
```suggestion
    println(listOfUser[0].name)
```

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    println(listOfUser.map(User::name).elementAt(listOfUser.size - 1))
тоже самое

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    fun updateCache() {
а это тут зачем?

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +inline fun auth(aut: () -> Unit, function: () -> Unit) {
функция auth должна принимать в себя юзера, authCallback и аргумент updateCache
Логика проверки возраста проводится там

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/User.kt
> +    fun nuiche(): Boolean {
Это не функция-расширение
Искать как extension function

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/User.kt
> +        return a
Функция не должна ничего возвращать
Она или выводит успех, или выбрасывает исключение
предлагаю вместо вывода зайти не получится выбрасывать исключение
Например, 
`throw IllegalStateException("Без объяснения причины")`

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    val reg = Action.Registration()
тут объекты создавать не надо

2022-09-16 15:07 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    when (a) {
Нужно проверять у Action подтип через when в связке со словом is.

https://kotlinlang.org/docs/sealed-classes.html#sealed-classes-and-when-expression

2022-09-16 16:58 UTC, igorkardin commented on src/main/kotlin/app.kt
> +inline fun auth(aut: () -> Unit, function: () -> Unit) {
я нихуя не понял как туда че передавать и как там логику проверки возраста сделать и вообще эта inline тема какая-то непонятная

2022-09-16 17:10 UTC, imadFndt commented on src/main/kotlin/app.kt
> +inline fun auth(aut: () -> Unit, function: () -> Unit) {
inline это обычная функция, которая вместо того чтобы храниться как функция, вставляется в место вызова когда проект компилируется. Ты это видишь как функцию, то что в итоге запускается – видит обычный подряд идущий код.
А тебе надо переделать саму функцию.
auth() это как с эйчарами контактировать. Соискатель(user) приходит, проходит какую-то проверку и результат узнает не тут же на месте, а через свой контакт (callback), эйчар же потом записывает куда-то данные по резюме, обновляет свой кеш (updateCache)
В итоге появится 
`inline fun auth(user: User, callback: AuthCallback, updateCache: () -> Unit)`

2022-09-17 12:31 UTC, imadFndt requested changes

2022-09-17 12:31 UTC, imadFndt commented on src/main/kotlin/User.kt
> +    val startTime: LocalTime by lazy { LocalTime.now() }
а как это работает?

2022-09-17 12:31 UTC, imadFndt commented on src/main/kotlin/app.kt
> +    if (user.age >= 18) {
бля ну все бы идеально
но у тебя есть функция nuiche, вот ее тут используй

2022-09-17 15:28 UTC, igorkardin commented on src/main/kotlin/User.kt
> +    val startTime: LocalTime by lazy { LocalTime.now() }
ну тут короче функция LocalTime.now() иницилизируется только один раз, т е время засекается ток один раз, даже после того как мы задержку в сенкудну ставим, время не меняется, поэтому в выводе в консоли два раза одинаковое время выходит

2022-09-17 15:29 UTC, imadFndt commented on src/main/kotlin/User.kt
> +    val startTime: LocalTime by lazy { LocalTime.now() }
а один раз это когда

2022-09-18 11:01 UTC, igorkardin commented on src/main/kotlin/User.kt
> +    val startTime: LocalTime by lazy { LocalTime.now() }
при втором вызове?

2022-09-18 11:02 UTC, imadFndt commented on src/main/kotlin/User.kt
> +    val startTime: LocalTime by lazy { LocalTime.now() }
неправильно

2022-09-18 13:59 UTC, imadFndt approved these changes

2022-09-18 14:37 UTC, merged